// Local, disposable integration environment. Never points at DATABASE_URL from .env.
import { PGlite } from '@electric-sql/pglite';
import { createServer, LogLevel } from 'pglite-server';
import { chromium } from '@playwright/test';
import { readFile,readdir,mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {authService}=require('../.tools/src/modules/auth/service.js');
const pg=new PGlite();
const adapter=executor=>({query:async(sql,params=[]) => (await executor.query(sql,params)).rows,transaction:fn=>pg.transaction(tx=>fn(adapter(tx)))});
let server,app,browser;const sockets=new Set();
const port=Number(process.env.TEST_PORT || 3107),origin=`http://127.0.0.1:${port}`;
let appOutput='';
try {
 const root=new URL('../prisma/migrations/',import.meta.url);
 for(const dir of (await readdir(root,{withFileTypes:true})).filter(d=>d.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name)))await pg.exec(await readFile(new URL(`${dir.name}/migration.sql`,root),'utf8'));
 const password=`Teste-${randomBytes(18).toString('base64url')}`;
 await authService(adapter(pg)).bootstrap({name:'Ana Martins',email:'ana@example.invalid',password,roleCode:'ADMIN'});
 server=createServer(pg,{logLevel:LogLevel.Error});server.on('connection',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const dbPort=server.address().port;
 app=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port',String(port)],{env:{...process.env,NEXT_TELEMETRY_DISABLED:'1',APP_ORIGIN:origin,DATABASE_URL:`postgresql://test:test@127.0.0.1:${dbPort}/postgres?connection_limit=1&connect_timeout=10`},stdio:['ignore','pipe','pipe'],windowsHide:true});
 app.stdout.on('data',data=>{appOutput+=data;});app.stderr.on('data',data=>{appOutput+=data;});
 let ready=false;
 for(let i=0;i<80;i++){try{if((await fetch(`${origin}/login`)).ok){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,250));}
 assert.ok(ready,'Next não iniciou.');
 const health=await fetch(`${origin}/api/health`);assert.equal(health.status,200);assert.deepEqual(await health.json(),{status:'ok'});
 const denied=await fetch(`${origin}/api/users`);assert.equal(denied.status,401);
 const csrf=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify({email:'ana@example.invalid',password})});assert.equal(csrf.status,403);
 browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:960}});
 const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`${origin}/login`);
 await mkdir('test-results',{recursive:true});
 await page.screenshot({path:'test-results/login-desktop.png',fullPage:true});
 await page.getByLabel('E-mail',{exact:true}).fill('ana@example.invalid');
 await page.getByLabel('Senha',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Entrar na minha loja'}).click();
 await page.waitForURL(`${origin}/`);
 assert.ok(await page.getByRole('heading',{name:'Olá, Ana.'}).isVisible());
 await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Minha conta',exact:true}).click();
 await page.getByRole('heading',{name:'Alterar senha',exact:true}).waitFor();
 await page.screenshot({path:'test-results/account-desktop.png',fullPage:true});
 const cookies=await context.cookies();const session=cookies.find(c=>c.name==='erp_session');
 assert.ok(session?.httpOnly);assert.equal(session.sameSite,'Strict');
 assert.ok(!await page.evaluate(()=>document.cookie.includes('erp_session')));
 await page.getByRole('link',{name:'Usuários',exact:true}).click();
 await page.getByRole('button',{name:'Novo usuário'}).click();
 await page.getByLabel('Nome',{exact:true}).fill('Bruno Souza');
 await page.getByLabel('E-mail',{exact:true}).fill('bruno@example.invalid');
 await page.getByLabel('Senha inicial',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Salvar usuário'}).click();
 await page.getByRole('status').filter({hasText:'Usuário criado'}).waitFor();
 await page.getByText('bruno@example.invalid',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Editar Bruno Souza',exact:true}).click();
 await page.getByLabel('Nome',{exact:true}).fill('Bruno Souza');
 await page.getByRole('button',{name:'Salvar usuário'}).click();
 await page.getByRole('status').filter({hasText:'Usuário atualizado'}).waitFor();
 assert.equal(await page.evaluate(async()=>{
  const {user}=await (await fetch('/api/auth/me')).json();
  return (await fetch(`/api/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:user.name,roleCode:'ADMIN',active:false})})).status;
 }),409);
 await page.screenshot({path:'test-results/users-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Produtos',exact:true}).click();
 await page.getByRole('link',{name:'Gerenciar categorias'}).click();
 await page.getByRole('button',{name:'Nova categoria',exact:false}).click();
 await page.getByLabel('Nome da categoria',{exact:true}).fill('Papelaria');
 await page.getByRole('button',{name:'Salvar categoria'}).click();
 await page.getByRole('status').filter({hasText:'Categoria salva.'}).waitFor();
 await page.getByRole('link',{name:'Voltar aos produtos',exact:false}).click();
 await page.getByRole('link',{name:'Novo produto',exact:false}).click();
 await page.getByLabel('Nome do produto',{exact:true}).fill('Caderno universitário 96 folhas');
 await page.getByLabel('Código interno',{exact:true}).fill('PAP-001');
 await page.getByLabel('Código de barras',{exact:true}).fill('0001234567890');
 await page.getByLabel('SKU',{exact:true}).fill('CAD-96');
 await page.getByLabel('Categoria',{exact:true}).selectOption({label:'Papelaria'});
 await page.getByLabel('Marca',{exact:true}).fill('Linha Essencial');
 await page.getByLabel('Descrição',{exact:true}).fill('Caderno espiral, capa dura e 96 folhas pautadas.');
 await page.getByLabel('Preço de custo',{exact:true}).fill('12,50');
 await page.getByLabel('Preço de venda',{exact:true}).fill('25,00');
 await page.getByLabel('Estoque mínimo',{exact:true}).fill('5');
 await page.getByLabel('Estoque máximo',{exact:true}).fill('100');
 await page.getByLabel('Localização no estoque',{exact:true}).fill('Prateleira A · posição 02');
 await page.getByRole('button',{name:'Salvar produto',exact:true}).click();
 await page.waitForURL(/\/produtos\/[a-f0-9-]{36}$/);
 const productPath=new URL(page.url()).pathname;
 await page.getByLabel('Preço de venda',{exact:true}).fill('24,90');
 await page.getByRole('button',{name:'Salvar produto',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Produto salvo.'}).waitFor();
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'test-results/product-editor-desktop.png',fullPage:true});
 // Populate the disposable catalog through real HTTP routes for a representative gallery.
 await page.evaluate(async()=>{
  const send=async(path,data)=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error('Falha ao preparar catálogo de demonstração.');return response.json();};
  const a=await send('/api/categories',{name:'Acessórios',active:true});
  const o=await send('/api/categories',{name:'Organização',active:true});
  const {categories}=await (await fetch('/api/categories')).json();const p=categories.find(c=>c.name==='Papelaria');
  for(const [name,code,cost,price,categoryId] of [['Caneta esferográfica azul','PAP-002','1.50','3.90',p.id],['Estojo de tecido','ACE-001','8.00','19.90',a.id],['Garrafa térmica 500 ml','ACE-002','24.50','49.90',a.id],['Organizador de mesa','ORG-001','14.00','32.00',o.id],['Bloco de notas adesivas','PAP-003','3.20','7.50',p.id]])await send('/api/products',{name,code,cost,price,categoryId,barcode:'',sku:'',description:'',brand:'',unit:'UN',minimum:'5',maximum:'',location:'',photoUrl:'',supplierIds:[],active:true});
 });
 await page.getByRole('link',{name:'Voltar à lista',exact:true}).click();
 await page.getByRole('link',{name:'Garrafa térmica 500 ml',exact:true}).waitFor();
 await page.getByLabel('Buscar produto',{exact:true}).fill('0001234567890');
 await page.getByRole('link',{name:'Garrafa térmica 500 ml',exact:true}).waitFor({state:'hidden'});
 await page.getByRole('link',{name:'Caderno universitário 96 folhas',exact:true}).waitFor();
 await page.getByLabel('Buscar produto',{exact:true}).fill('');
 await page.getByRole('link',{name:'Garrafa térmica 500 ml',exact:true}).waitFor();
 await page.screenshot({path:'test-results/products-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Gerenciar categorias'}).click();
 await page.getByRole('button',{name:'Editar Organização',exact:true}).waitFor();
 await page.screenshot({path:'test-results/categories-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Estoque',exact:true}).click();
 await page.getByRole('button',{name:'Movimentar Caderno universitário 96 folhas',exact:true}).click();
 await page.getByLabel('Quantidade',{exact:true}).fill('12');
 await page.getByLabel('Motivo da movimentação',{exact:true}).fill('Recebimento de mercadorias de demonstração');
 await page.getByRole('button',{name:'Registrar movimentação',exact:true}).click();
 await page.getByTestId('stock-current').filter({hasText:'12,000'}).waitFor();
 await page.getByLabel('Tipo de movimentação',{exact:true}).selectOption('LOSS');
 await page.getByLabel('Quantidade',{exact:true}).fill('2');
 await page.getByLabel('Motivo da movimentação',{exact:true}).fill('Perda identificada na conferência');
 await page.getByRole('button',{name:'Registrar movimentação',exact:true}).click();
 await page.getByTestId('stock-current').filter({hasText:'10,000'}).waitFor();
 const lossRow=page.locator('tr').filter({hasText:'Perda identificada na conferência'});
 await lossRow.getByRole('button',{name:'Estornar movimento',exact:false}).click();
 await page.getByLabel('Motivo do estorno',{exact:true}).fill('Correção: mercadoria localizada em outra prateleira');
 await page.getByRole('button',{name:'Confirmar estorno',exact:true}).click();
 await page.getByTestId('stock-current').filter({hasText:'12,000'}).waitFor();
 await page.getByLabel('Tipo de movimentação',{exact:true}).selectOption('ADJUSTMENT');
 await page.getByLabel('Quantidade contada',{exact:true}).fill('4');
 await page.getByLabel('Motivo da movimentação',{exact:true}).fill('Contagem física da prateleira de demonstração');
 await page.getByRole('button',{name:'Registrar movimentação',exact:true}).click();
 await page.getByTestId('stock-current').filter({hasText:'4,000'}).waitFor();
 // Explicit stock writes use new idempotency keys; subsequent replay must not duplicate.
 assert.equal(await page.evaluate(async()=>{const w=await(await fetch('/api/stock/warehouses')).json();const p=await(await fetch('/api/products?q=PAP-001')).json();const data={warehouseId:w.warehouses[0].id,productId:p.products[0].id,operationKey:crypto.randomUUID(),kind:'DAMAGE',quantity:'9',notes:'Saída acima do saldo atual'};return(await fetch('/api/stock/movements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).status;}),409);
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.getByRole('button',{name:'Movimentar Caderno universitário 96 folhas',exact:true}).waitFor();
 await page.screenshot({path:'test-results/stock-history-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Fechar histórico',exact:true}).click();
 await page.screenshot({path:'test-results/stock-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/stock-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow na tela de estoque');
 await page.getByRole('button',{name:'Movimentar Caderno universitário 96 folhas',exact:true}).click();
 await page.getByLabel('Quantidade',{exact:true}).waitFor();
 await page.screenshot({path:'test-results/stock-history-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow no histórico de estoque');
 await page.getByRole('link',{name:'Produtos',exact:true}).click();
 await page.getByRole('link',{name:'Gerenciar categorias'}).click();
 await page.getByRole('button',{name:'Editar Organização',exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/categories-mobile.png',fullPage:true});
 await page.getByRole('link',{name:'Voltar aos produtos',exact:false}).click();
 await page.getByRole('link',{name:'Garrafa térmica 500 ml',exact:true}).waitFor();
 await page.screenshot({path:'test-results/products-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow no catálogo móvel');
 await page.goto(`${origin}${productPath}`);
 await page.getByLabel('Nome do produto',{exact:true}).waitFor();
 await page.screenshot({path:'test-results/product-editor-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow no cadastro móvel');
 await page.getByRole('link',{name:'Usuários',exact:true}).click();
 await page.getByText('bruno@example.invalid',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/users-mobile.png',fullPage:true});
 const viewport=await page.evaluate(()=>({width:window.innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('*')].map(e=>({tag:e.tagName,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).filter(e=>e.right>window.innerWidth)}));
 if(viewport.scroll>viewport.width) console.log('Layout diagnostic',JSON.stringify(viewport));
 assert.ok(viewport.scroll<=viewport.width,'Overflow horizontal da página');
 await page.setViewportSize({width:1440,height:960});
 await page.getByRole('link',{name:'Clientes',exact:true}).click();
 await page.getByRole('button',{name:'Novo cliente',exact:false}).click();
 await page.getByLabel('Nome',{exact:true}).fill('Mariana Costa — demonstração');
 await page.getByLabel('E-mail',{exact:true}).fill('mariana@example.invalid');
 await page.getByLabel('Cidade',{exact:true}).fill('Cuiabá');
 await page.getByLabel('Estado (UF)',{exact:true}).fill('MT');
 await page.getByLabel('Data de nascimento',{exact:true}).fill('1990-05-20');
 await page.getByLabel('Observações',{exact:true}).fill('Cadastro fictício para apresentar as telas da loja.');
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/customer-editor-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/customer-editor-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow no cadastro de cliente');
 await page.getByRole('button',{name:'Salvar cliente',exact:true}).click();
 await page.getByRole('button',{name:'Editar cliente',exact:true}).waitFor();
 await page.getByRole('button',{name:'Ver Mariana Costa — demonstração',exact:true}).waitFor();
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/customer-detail-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow na ficha do cliente');
 await page.setViewportSize({width:1440,height:960});
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/customer-detail-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Editar cliente',exact:true}).click();
 await page.getByLabel('Cliente ativo',{exact:true}).uncheck();
 await page.getByRole('button',{name:'Salvar cliente',exact:true}).click();
 await page.getByRole('button',{name:'Editar cliente',exact:true}).waitFor();
 await page.getByRole('button',{name:'Fechar ficha',exact:true}).click();
 await page.getByLabel('Situação',{exact:true}).selectOption('inactive');
 await page.getByRole('button',{name:'Ver Mariana Costa — demonstração',exact:true}).click();
 await page.getByRole('button',{name:'Editar cliente',exact:true}).click();
 await page.getByLabel('Cliente ativo',{exact:true}).check();
 await page.getByRole('button',{name:'Salvar cliente',exact:true}).click();
 await page.getByRole('button',{name:'Editar cliente',exact:true}).waitFor();
 await page.getByRole('button',{name:'Fechar ficha',exact:true}).click();
 await page.getByLabel('Situação',{exact:true}).selectOption('active');
 await page.getByLabel('Buscar cliente',{exact:true}).fill('mariana@example.invalid');
 await page.getByRole('button',{name:'Ver Mariana Costa — demonstração',exact:true}).waitFor();
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/customers-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/customers-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:960});
 await page.getByRole('link',{name:'Vendas',exact:true}).click();
 await page.getByRole('button',{name:'Caixa da venda',exact:true}).click();
 await page.getByLabel('Saldo inicial em dinheiro',{exact:true}).fill('100');
 await page.getByRole('button',{name:'Abrir caixa',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Caixa aberto.'}).waitFor();
 await page.getByRole('button',{name:'Caixa da venda',exact:true}).click();
 await page.getByRole('button',{name:'Nova venda',exact:false}).click();
 await page.getByLabel('Buscar produto',{exact:true}).fill('0001234567890');
 await page.getByRole('button',{name:/Caderno universitário 96 folhas.*Adicionar/}).click();
 await page.getByLabel('Quantidade de Caderno universitário 96 folhas',{exact:true}).fill('2');
 await page.getByLabel('Desconto total (R$)',{exact:true}).fill('5');
 await page.getByLabel('Motivo do desconto',{exact:true}).fill('Desconto comercial de demonstração');
 await page.getByLabel('Cliente da venda',{exact:true}).selectOption({label:'Mariana Costa — demonstração'});
 await page.mouse.move(1300,0);
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sale-editor-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sale-editor-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow na venda rápida');
 await page.getByRole('button',{name:'Salvar venda aberta',exact:true}).click();
 await page.getByRole('button',{name:'Finalizar venda',exact:true}).waitFor();
 await page.getByLabel('Dinheiro',{exact:true}).fill('20');
 await page.getByLabel('PIX',{exact:true}).fill('24,80');
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sale-payment-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:960});
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sale-payment-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Finalizar venda',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Venda finalizada.'}).waitFor();
 const finalized=await page.evaluate(async()=>{const list=await(await fetch('/api/sales')).json();const d=await(await fetch('/api/sales/'+list.sales[0].id)).json();const p=await(await fetch('/api/products?q=PAP-001')).json();return {d,stock:p.products[0].stock};});
 assert.equal(finalized.d.sale.status,'FINALIZED');assert.equal(finalized.d.sale.total,'44.80');assert.equal(finalized.d.payments.length,2);assert.equal(finalized.stock,'2.000');
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sale-detail-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sale-detail-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow no comprovante interno');
 await page.getByRole('button',{name:'Cancelar venda',exact:true}).click();
 await page.getByLabel('Motivo do cancelamento',{exact:true}).fill('Devolução integral conferida no balcão');
 await page.getByRole('button',{name:'Confirmar cancelamento',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Venda cancelada.'}).waitFor();
 assert.equal(await page.evaluate(async()=>{const p=await(await fetch('/api/products?q=PAP-001')).json();return p.products[0].stock;}),'4.000');
 await page.getByRole('button',{name:'Fechar venda',exact:true}).click();
 await page.getByRole('button',{name:'Abrir venda 1',exact:true}).waitFor();
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sales-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:960});
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 await page.mouse.move(1300,0);
 await page.screenshot({path:'test-results/sales-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Caixa da venda',exact:true}).click();
 await page.getByLabel('Dinheiro contado',{exact:true}).fill('100');
 await page.getByRole('button',{name:'Fechar caixa',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Caixa fechado.'}).waitFor();
 await page.getByRole('button',{name:'Sair da conta'}).click();await page.waitForURL(`${origin}/login`);
 await page.getByLabel('E-mail',{exact:true}).fill('bruno@example.invalid');await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar na minha loja'}).click();await page.waitForURL(`${origin}/conta`);
 await page.getByText('Antes de continuar',{exact:false}).waitFor();
 await page.getByLabel('Senha atual',{exact:true}).fill(password);
 const nextPassword=`Outra-${randomBytes(18).toString('base64url')}`;
 await page.getByLabel('Nova senha',{exact:true}).fill(nextPassword);await page.getByLabel('Confirmar nova senha',{exact:true}).fill(nextPassword);
 await page.getByRole('button',{name:'Salvar nova senha'}).click();await page.waitForURL(`${origin}/login`);
 await page.getByLabel('E-mail',{exact:true}).fill('bruno@example.invalid');await page.getByLabel('Senha',{exact:true}).fill(nextPassword);await page.getByRole('button',{name:'Entrar na minha loja'}).click();await page.waitForURL(`${origin}/`);
 assert.equal(await page.evaluate(async()=> (await fetch('/api/users')).status),403);
 assert.equal(await page.getByRole('link',{name:'Usuários',exact:true}).count(),0);
 await page.getByRole('link',{name:'Produtos',exact:true}).click();
 await page.getByRole('link',{name:'Caderno universitário 96 folhas',exact:true}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Novo produto',exact:false}).count(),0);
 const sellerCatalog=await page.evaluate(async()=>{const response=await fetch('/api/products');const data=await response.json();const created=await fetch('/api/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Não autorizada',active:true})});return {product:data.products[0],writeStatus:created.status};});
 assert.equal(sellerCatalog.writeStatus,403);assert.ok(!('cost'in sellerCatalog.product));assert.ok(!('margin'in sellerCatalog.product));
 assert.equal(await page.evaluate(async()=> (await fetch('/api/stock/warehouses')).status),403);
 assert.equal(await page.getByRole('link',{name:'Estoque',exact:true}).count(),0);
 await page.getByRole('link',{name:'Vendas',exact:true}).click();
 await page.getByRole('button',{name:'Nova venda',exact:false}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Caixa da venda',exact:true}).count(),0);
 assert.equal(await page.evaluate(async()=>(await fetch('/api/sales/cash')).status),403);
 await page.getByRole('link',{name:'Clientes',exact:true}).click();
 await page.getByRole('button',{name:'Ver Mariana Costa — demonstração',exact:true}).click();
 await page.getByRole('heading',{name:'Histórico de compras',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Editar cliente',exact:true}).count(),0);
 assert.equal(await page.evaluate(async()=>(await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Negado'})})).status),403);
 await page.getByRole('button',{name:'Sair da conta'}).click();await page.waitForURL(`${origin}/login`);
 await page.screenshot({path:'test-results/login-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Browser: venda à vista, pagamento misto, caixa, cancelamento integral, autenticação, catálogo, cadastro/edição/reativação de clientes, entradas/perdas/contagem, estorno de estoque, bloqueio de saldo negativo, permissões e telas desktop/celular aprovados.');
} catch(error) {console.error(appOutput.slice(-5000));throw error;}
finally {
 if(browser)await browser.close();
 if(app){app.kill();await new Promise(resolve=>{app.once('exit',resolve);setTimeout(resolve,3000);});}
 for(const socket of sockets)socket.destroy();
 if(server)await new Promise(resolve=>server.close(resolve));
 await pg.close();
}

