'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import type { CatalogProduct,Category } from '../modules/catalog/service';
import { money } from '../modules/catalog/decimal';
import { api } from './forms';
export function ProductList({manage}:{manage:boolean}){
 const [rows,setRows]=useState<CatalogProduct[]>([]),[categories,setCategories]=useState<Category[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('active'),[categoryId,setCategory]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{api('/api/categories','GET').then(data=>setCategories(data.categories)).catch(e=>setError(e.message));},[]);
 useEffect(()=>{
  const controller=new AbortController();setLoading(true);setError('');
  const timer=setTimeout(async()=>{try{const response=await fetch(`/api/products?${new URLSearchParams({q,status,categoryId,page:String(page)})}`,{signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error);setRows(result.products);setTotal(result.total);setLoading(false);}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Não foi possível carregar.');setLoading(false);}}},200);
  return()=>{clearTimeout(timer);controller.abort();};
 },[q,status,categoryId,page,retry]);
 return <><div className="toolbar"><Link href="/categorias" className="text-link">Gerenciar categorias →</Link>{manage&&<Link className="button" href="/produtos/novo">+ Novo produto</Link>}</div><div className="catalog-filters"><label>Buscar produto<input value={q} maxLength={100} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Nome, código, SKU ou código de barras"/></label><label>Categoria<select aria-label="Categoria" value={categoryId} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">Todas as categorias</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}{!c.active?' (inativa)':''}</option>)}</select></label><label>Situação<select aria-label="Situação" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select></label></div>{error&&<div className="error" role="alert">{error} <button className="secondary" onClick={()=>setRetry(n=>n+1)}>Tentar novamente</button></div>}<section className="card users-table catalog-table"><div className="section-heading"><h2>Catálogo <span className="count">{total}</span></h2><span className="muted">25 por página</span></div>{loading?<p className="empty" role="status">Carregando produtos…</p>:!error&&rows.length?<div className="table-scroll"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço de venda</th>{manage&&<th>Margem bruta</th>}<th>Estoque atual</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><Link className="product-name" href={`/produtos/${p.id}`}>{p.name}</Link><small>{p.code}{p.sku?` · SKU ${p.sku}`:''}</small></td><td data-label="Categoria">{p.categoryName??'Sem categoria'}</td><td data-label="Preço de venda">{money(p.price)}</td>{manage&&<td data-label="Margem bruta">{p.margin===null?'—':`${p.margin?.replace('.',',')}%`}</td>}<td data-label="Estoque atual">{p.stock.replace('.',',')} {p.unit}</td><td data-label="Situação"><span className={`status ${p.active?'active':'inactive'}`}>{p.active?'Ativo':'Inativo'}</span></td><td><Link className="secondary button" href={`/produtos/${p.id}`} aria-label={`${manage?'Editar':'Consultar'} ${p.name}`}>{manage?'Editar':'Consultar'}</Link></td></tr>)}</tbody></table></div>:!error&&<div className="empty"><h3>Nenhum produto encontrado</h3><p>{q||categoryId||status!=='active'?'Experimente ajustar os filtros.':'Cadastre o primeiro produto para começar.'}</p></div>}<div className="pagination"><span>Página {page} de {Math.max(1,Math.ceil(total/25))}</span><div><button className="secondary" disabled={page===1||loading} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="secondary" disabled={page*25>=total||loading} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></div></section><p className="stage-note">O estoque é calculado pelas movimentações. Entradas e ajustes são registrados na tela de estoque.</p></>;
}



