'use client';
import { useEffect,useState,type FormEvent } from 'react';
import Link from 'next/link';
import { api } from './forms';
import type { Category } from '../modules/catalog/service';
export function CategoryManager({manage}:{manage:boolean}){
 const [rows,setRows]=useState<Category[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Category|null|undefined>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const result=await api('/api/categories','GET');setRows(result.categories);setLoading(false);}
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false);});},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');setBusy(true);const form=new FormData(event.currentTarget);try{await api(editing?`/api/categories/${editing.id}`:'/api/categories',editing?'PATCH':'POST',{name:form.get('name'),active:form.get('active')==='on',...(editing?{version:editing.version}:{})});setEditing(undefined);await load();setMessage('Categoria salva.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <><div className="toolbar"><Link href="/produtos" className="text-link">← Voltar aos produtos</Link>{manage&&<button onClick={()=>{setEditing(null);setError('');setMessage('');}}>+ Nova categoria</button>}</div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}{editing!==undefined&&<section className="card editor"><div className="section-heading"><h2>{editing?'Editar categoria':'Nova categoria'}</h2><button className="secondary" disabled={busy} onClick={()=>setEditing(undefined)}>Fechar</button></div><form key={editing?.id??'new'} className="form" onSubmit={submit}><label>Nome da categoria<input name="name" required maxLength={120} defaultValue={editing?.name}/></label><label className="checkbox"><input type="checkbox" name="active" defaultChecked={editing?.active??true}/>Categoria ativa</label><p className="muted">Desativar impede novas associações. Os produtos já vinculados preservam sua categoria.</p><button disabled={busy}>{busy?'Salvando…':'Salvar categoria'}</button></form></section>}<section className="card users-table"><div className="section-heading"><h2>Categorias da loja <span className="count">{rows.length}</span></h2></div>{loading?<p className="empty" role="status">Carregando categorias…</p>:rows.length?<div className="table-scroll"><table><thead><tr><th>Categoria</th><th>Produtos</th><th>Situação</th>{manage&&<th>Ações</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.productCount}</td><td><span className={`status ${row.active?'active':'inactive'}`}>{row.active?'Ativa':'Inativa'}</span></td>{manage&&<td><button className="secondary" aria-label={`Editar ${row.name}`} onClick={()=>{setEditing(row);setError('');setMessage('');window.scrollTo({top:0,behavior:'smooth'});}}>Editar</button></td>}</tr>)}</tbody></table></div>:<p className="empty">Nenhuma categoria cadastrada. {manage?'Crie a primeira para organizar seu catálogo.':''}</p>}</section></>;
}
