'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {api} from './forms';
import type {Customer} from '../modules/customers/service';
const money=(v:string)=>{const [a,b='00']=v.split('.');return 'R$ '+a.replace(/\B(?=(\d{3})+(?!\d))/g,'.')+','+b.padEnd(2,'0');};
const date=(v:string|null)=>v?new Date(v.length===10?v+'T12:00:00Z':v).toLocaleDateString('pt-BR',{timeZone:'America/Cuiaba'}):'—';
type Summary={creditLimit:string;used:string;available:string;totalPurchased:string;purchaseCount:number;lastPurchase:string|null};
type History={sales:{id:string;number:number;status:string;total:string;createdAt:string}[];payments:{id:string;direction:string;method:string;amount:string;createdAt:string;reversesId:string|null}[];hasMore:boolean;page:number};
const statuses:Record<string,string>={OPEN:'Aberta',FINALIZED:'Finalizada',CANCELLED:'Cancelada',PARTIALLY_RETURNED:'Devolução parcial',RETURNED:'Devolvida'};
const methods:Record<string,string>={CASH:'Dinheiro',PIX:'PIX',DEBIT_CARD:'Débito',CREDIT_CARD:'Crédito',STORE_CREDIT:'A prazo'};
const groups:{legend:string;fields:[keyof Customer,string,number,string?][]}[]=[
 {legend:'Identificação',fields:[['name','Nome',180],['tradeName','Nome fantasia',180],['cpf','CPF',18],['cnpj','CNPJ',22],['rg','RG',30],['birthDate','Data de nascimento',10,'date']]},
 {legend:'Contato',fields:[['phone','Telefone',30,'tel'],['whatsapp','WhatsApp',30,'tel'],['email','E-mail',254,'email']]},
 {legend:'Endereço',fields:[['postalCode','CEP',10],['street','Endereço',200],['number','Número',30],['neighborhood','Bairro',100],['city','Cidade',100],['state','Estado (UF)',2]]}
];
export function Customers({manage}:{manage:boolean}){
 const [rows,setRows]=useState<Customer[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('active'),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<Customer|null>(null),[editing,setEditing]=useState<Customer|null|undefined>(),[summary,setSummary]=useState<Summary|null>(null),[history,setHistory]=useState<History|null>(null),[busy,setBusy]=useState(false),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const request=useRef(0),listRequest=useRef(0);
 useEffect(()=>{const n=++listRequest.current;setLoading(true);const timer=setTimeout(()=>{api('/api/customers?'+new URLSearchParams({q,status,page:String(page)}),'GET').then(r=>{if(n===listRequest.current){setRows(r.customers);setTotal(r.total);}}).catch(e=>{if(n===listRequest.current)setError(e.message);}).finally(()=>{if(n===listRequest.current)setLoading(false);});},200);return()=>{clearTimeout(timer);++listRequest.current;};},[q,status,page,refresh]);
 async function open(id:string,historyPage=1){
  const n=++request.current;setError('');setDetailLoading(true);setEditing(undefined);setSelected(null);setSummary(null);setHistory(null);
  try{const [c,s,h]=await Promise.all([api('/api/customers/'+id,'GET'),api('/api/customers/'+id+'/summary','GET'),api('/api/customers/'+id+'/history?page='+historyPage,'GET')]);if(n===request.current){setSelected(c);setSummary(s);setHistory(h);window.scrollTo({top:0,behavior:'smooth'});}}
  catch(e){if(n===request.current)setError(e instanceof Error?e.message:'Não foi possível abrir o cliente.');}
  finally{if(n===request.current)setDetailLoading(false);}
 }
 function close(){++request.current;setSelected(null);setSummary(null);setHistory(null);setEditing(undefined);setDetailLoading(false);}
 async function save(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setError('');setMessage('');setBusy(true);const form=new FormData(event.currentTarget),data={...Object.fromEntries(form),active:form.get('active')==='on',...(editing?{version:editing.version}:{})};
  try{const c=await api(editing?'/api/customers/'+editing.id:'/api/customers',editing?'PATCH':'POST',data);setEditing(undefined);setRefresh(v=>v+1);setMessage('Cliente salvo.');await open(c.id);}
  catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}
 }
 return <>
 <div className="toolbar"><p className="muted">{manage?'Cadastre e mantenha os contatos atualizados.':'Consulta de clientes da loja.'}</p>{manage&&<button disabled={busy} onClick={()=>{close();setEditing(null);setError('');setMessage('');}}>+ Novo cliente</button>}</div>
 {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}
 {editing!==undefined&&<section className="card editor"><div className="section-heading"><h2>{editing?'Editar cliente':'Novo cliente'}</h2><button className="secondary" disabled={busy} onClick={()=>setEditing(undefined)}>Fechar cadastro</button></div><form className="product-form customer-form" onSubmit={save} key={editing?.id??'new'}>
 {groups.map(g=><fieldset key={g.legend} disabled={busy}><legend>{g.legend}</legend><div className="form-grid">{g.fields.map(([key,label,max,type])=><label key={key}>{label}<input name={key} type={type??'text'} required={key==='name'} maxLength={max} defaultValue={String(editing?.[key]??'')} autoComplete="off"/></label>)}</div></fieldset>)}
 <label>Observações<textarea name="notes" rows={3} maxLength={2000} defaultValue={editing?.notes??''} disabled={busy}/></label><label className="checkbox"><input name="active" type="checkbox" defaultChecked={editing?.active??true} disabled={busy}/>Cliente ativo</label><p className="input-help">Somente o nome é obrigatório. Desativar preserva o cadastro e o histórico. CPF e CNPJ são verificados quanto ao formato; não há consulta cadastral externa.</p>
 <div className="editor-actions"><button disabled={busy}>{busy?'Salvando…':'Salvar cliente'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(undefined)}>Cancelar</button></div></form></section>}
 {detailLoading&&<p role="status" className="empty">Carregando ficha…</p>}
 {selected&&summary&&history&&editing===undefined&&<section className="card editor customer-detail"><div className="section-heading"><div><h2>{selected.name}</h2><p className="muted">{selected.tradeName??'Ficha do cliente'} · {selected.active?'Ativo':'Inativo'}</p></div><div className="editor-actions">{manage&&<button className="secondary" onClick={()=>{setEditing(selected);setError('');setMessage('');}}>Editar cliente</button>}<button className="secondary" onClick={close}>Fechar ficha</button></div></div>
 <div className="customer-metrics">{[['Total comprado',money(summary.totalPurchased)],['Compras',String(summary.purchaseCount)],['Última compra',date(summary.lastPurchase)],['Saldo devedor',money(summary.used)],['Limite de crédito',money(summary.creditLimit)],['Crédito disponível',money(summary.available)]].map(([label,value])=><section key={label}><small>{label}</small><strong>{value}</strong></section>)}</div><p className="input-help">Total comprado considera o valor original das vendas finalizadas, inclusive as devolvidas. Crédito e recebimentos serão operados nas próximas etapas.</p>
 <dl className="customer-data">{groups.flatMap(g=>g.fields).filter(([key])=>key!=='name').map(([key,label])=><div key={key}><dt>{label}</dt><dd>{key==='birthDate'?date(selected.birthDate):String(selected[key]??'—')}</dd></div>)}<div><dt>Data de cadastro</dt><dd>{date(selected.createdAt)}</dd></div><div><dt>Última atualização</dt><dd>{date(selected.updatedAt)}</dd></div><div className="customer-notes"><dt>Observações</dt><dd>{selected.notes??'—'}</dd></div></dl>
 <h3 className="history-title">Histórico de compras</h3>{history.sales.length?<div className="table-scroll"><table><thead><tr><th>Venda</th><th>Data</th><th>Situação</th><th>Valor original</th></tr></thead><tbody>{history.sales.map(s=><tr key={s.id}><td>#{s.number}</td><td>{date(s.createdAt)}</td><td>{statuses[s.status]??s.status}</td><td>{money(s.total)}</td></tr>)}</tbody></table></div>:<p className="empty">Nenhuma compra registrada.</p>}
 <h3 className="history-title">Histórico de pagamentos</h3>{history.payments.length?<div className="table-scroll"><table><thead><tr><th>Data</th><th>Movimento</th><th>Forma</th><th>Valor do cliente</th></tr></thead><tbody>{history.payments.map(p=><tr key={p.id}><td>{date(p.createdAt)}</td><td>{p.reversesId?'Estorno':p.direction==='IN'?'Recebimento':'Saída'}</td><td>{methods[p.method]??p.method}</td><td>{money(p.amount)}</td></tr>)}</tbody></table></div>:<p className="empty">Nenhum pagamento registrado.</p>}
 <div className="pagination"><span>Página {history.page} · Até 25 registros por histórico</span><div><button className="secondary" disabled={history.page===1} onClick={()=>open(selected.id,history.page-1)}>Histórico anterior</button><button className="secondary" disabled={!history.hasMore} onClick={()=>open(selected.id,history.page+1)}>Próximo histórico</button></div></div></section>}
 <div className="catalog-filters customer-filters"><label>Buscar cliente<input value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Nome, documento, e-mail ou telefone" maxLength={180}/></label><label>Situação<select aria-label="Situação" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select></label></div>
 <section className="card users-table catalog-table"><div className="section-heading"><h2>Clientes da loja <span className="count">{total}</span></h2></div>{loading?<p role="status" className="empty">Carregando clientes…</p>:rows.length?<div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Documento</th><th>Contato</th><th>Cidade</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.tradeName}</small></td><td data-label="Documento">{c.cpf??c.cnpj??'—'}</td><td data-label="Contato">{c.whatsapp??c.phone??c.email??'—'}</td><td data-label="Cidade">{[c.city,c.state].filter(Boolean).join(' / ')||'—'}</td><td data-label="Situação"><span className={'status '+(c.active?'active':'inactive')}>{c.active?'Ativo':'Inativo'}</span></td><td><button disabled={busy} className="secondary" aria-label={'Ver '+c.name} onClick={()=>open(c.id)}>Ver ficha</button></td></tr>)}</tbody></table></div>:<p className="empty">Nenhum cliente encontrado. Ajuste a busca ou cadastre um cliente.</p>}<div className="pagination"><span>Página {page} · {total} clientes</span><div><button className="secondary" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></div></section></>;
}
