'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from './forms';
import {cents,fixed} from '../modules/sales/validation';
import type {salesService} from '../modules/sales/service';
type Detail=Awaited<ReturnType<ReturnType<typeof salesService>['get']>>;
type Row=Detail['sale'];
type Product={id:string;name:string;code:string;unit:string;price:string;stock:string};
type Line=Product&{quantity:string};
type Option={id:string;name:string};
type Cash={registers:Option[];sessions:{id:string;name:string;openedBy:string;cashBalance:string}[]};
const methods=[['CASH','Dinheiro'],['PIX','PIX'],['DEBIT_CARD','Cartão de débito'],['CREDIT_CARD','Cartão de crédito']] as const;
const statuses:Record<string,string>={OPEN:'Aberta',FINALIZED:'Finalizada',CANCELLED:'Cancelada',PARTIALLY_RETURNED:'Devolução parcial',RETURNED:'Devolvida'};
function money(v:string){const [a,b='00']=v.split('.');return 'R$ '+a.replace(/\B(?=(\d{3})+(?!\d))/g,'.')+','+b;}
function parse(v:string,scale:number){if(!new RegExp('^\\d{1,16}(?:[.,]\\d{1,'+scale+'})?$').test(v))return null;const [a,b='']=v.replace(',','.').split('.');return BigInt(a+b.padEnd(scale,'0'));}
export function Sales({create,finalize,manage,cashManage,initialSaleId}:{create:boolean;finalize:boolean;manage:boolean;cashManage:boolean;initialSaleId?:string}){
 const [rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState('ALL'),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const [options,setOptions]=useState<{warehouses:Option[];sellers:Option[]}>({warehouses:[],sellers:[]}),[warehouse,setWarehouse]=useState(''),[seller,setSeller]=useState(''),[products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(''),[customerQ,setCustomerQ]=useState(''),[customers,setCustomers]=useState<Option[]>([]),[customer,setCustomer]=useState('');
 const [cart,setCart]=useState<Line[]>([]),[draft,setDraft]=useState(false),[discount,setDiscount]=useState('0'),[discountReason,setDiscountReason]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[payments,setPayments]=useState<Record<string,string>>({}),[reason,setReason]=useState('');
 const [cash,setCash]=useState<Cash>({registers:[],sessions:[]}),[session,setSession]=useState(''),[register,setRegister]=useState(''),[opening,setOpening]=useState('0'),[counted,setCounted]=useState(''),[showCash,setShowCash]=useState(false),[showCancel,setShowCancel]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const keys=useRef<Record<string,{signature:string;key:string}>>({}),selection=useRef(0);
 function keyed(name:string,data:Record<string,unknown>){const signature=JSON.stringify(data);if(keys.current[name]?.signature!==signature)keys.current[name]={signature,key:crypto.randomUUID()};return {...data,operationKey:keys.current[name].key};}
 async function loadCash(){if(!finalize)return;const c=await api('/api/sales/cash','GET');setCash(c);setRegister(v=>v||c.registers[0]?.id||'');setSession(v=>c.sessions.some((s:{id:string})=>s.id===v)?v:c.sessions[0]?.id||'');}
 useEffect(()=>{api('/api/sales/options','GET').then(o=>{setOptions(o);setWarehouse(o.warehouses[0]?.id??'');setSeller(o.sellers[0]?.id??'');}).catch(e=>setError(e.message));loadCash().catch(e=>setError(e.message));},[]);
 useEffect(()=>{let active=true;setLoading(true);api('/api/sales?'+new URLSearchParams({status,page:String(page)}),'GET').then(r=>{if(active){setRows(r.sales);setTotal(r.total);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[page,status,refresh]);
 useEffect(()=>{let active=true;if(!draft||!warehouse)return;const timer=setTimeout(()=>{api('/api/sales/lookup?'+new URLSearchParams({kind:'products',q,warehouseId:warehouse}),'GET').then(r=>{if(active)setProducts(r.products);}).catch(e=>{if(active)setError(e.message);});},200);return()=>{active=false;clearTimeout(timer);};},[q,warehouse,draft]);
 useEffect(()=>{let active=true;if(!draft)return;const timer=setTimeout(()=>{api('/api/sales/lookup?'+new URLSearchParams({kind:'customers',q:customerQ}),'GET').then(r=>{if(active)setCustomers(r.customers);}).catch(e=>{if(active)setError(e.message);});},200);return()=>{active=false;clearTimeout(timer);};},[customerQ,draft]);
 async function open(id:string){const n=++selection.current;setBusy(true);setError('');try{const d=await api('/api/sales/'+id,'GET');if(n===selection.current){setDetail(d);setDraft(false);setPayments({CASH:d.sale.total});setShowCancel(false);setReason('');window.scrollTo({top:0,behavior:'smooth'});}}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir.');}finally{setBusy(false);}}
 useEffect(()=>{if(initialSaleId)void open(initialSaleId);},[initialSaleId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();setRefresh(v=>v+1);await loadCash();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{setBusy(false);}}
 const discountValue=parse(discount,2);let subtotal=0n,valid=cart.length>0;
 for(const l of cart){const qty=parse(l.quantity,3);if(qty===null||qty<=0n){valid=false;continue;}subtotal+=(qty*cents(l.price)+500n)/1000n;}
 const cartTotal=discountValue===null?null:subtotal-discountValue;
 const paid=methods.reduce((sum,[key])=>sum+(parse(payments[key]||'0',2)??0n),0n);
 return <>
 <div className="toolbar"><p className="muted">Pagamentos à vista · Estoque atualizado ao finalizar</p><div className="editor-actions">{finalize&&<button className="secondary" onClick={()=>setShowCash(v=>!v)} disabled={busy}>Caixa da venda</button>}{create&&<button disabled={busy} onClick={()=>{setDraft(true);setDetail(null);setCart([]);setDiscount('0');setDiscountReason('');setCustomer('');setQ('');setError('');setMessage('');delete keys.current.create;}}>+ Nova venda</button>}</div></div>
 {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}
 {showCash&&<section className="card editor"><h2>Caixa da venda</h2><p className="input-help">PIX e cartões são registrados por método e não aumentam o saldo físico. Confira os pagamentos na maquininha ou no banco.</p><div className="form-grid">
 <div className="form"><label>Caixa aberto<select aria-label="Caixa aberto" value={session} onChange={e=>setSession(e.target.value)} disabled={busy}><option value="">Nenhum selecionado</option>{cash.sessions.map(s=><option key={s.id} value={s.id}>{s.name} · {s.openedBy}</option>)}</select></label><p>Dinheiro esperado: <strong>{money(cash.sessions.find(s=>s.id===session)?.cashBalance??'0.00')}</strong></p>{cashManage&&session&&<><label>Dinheiro contado<input value={counted} onChange={e=>setCounted(e.target.value)} inputMode="decimal" disabled={busy}/></label><button className="secondary" disabled={busy||parse(counted,2)===null} onClick={()=>run(async()=>{const r=await api('/api/sales/cash/close','POST',keyed('close',{sessionId:session,countedBalance:counted}));setMessage('Caixa fechado.'+(r.difference?' Diferença: '+money(r.difference):''));setCounted('');})}>Fechar caixa</button></>}</div>
 {cashManage&&<div className="form"><label>Caixa para abertura<select aria-label="Caixa para abertura" value={register} onChange={e=>setRegister(e.target.value)} disabled={busy}>{cash.registers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Saldo inicial em dinheiro<input value={opening} onChange={e=>setOpening(e.target.value)} inputMode="decimal" disabled={busy}/></label><button disabled={busy||!register} onClick={()=>run(async()=>{const r=await api('/api/sales/cash/open','POST',keyed('open',{registerId:register,openingBalance:opening}));setSession(r.id);setMessage('Caixa aberto.');delete keys.current.open;})}>Abrir caixa</button></div>}
 </div></section>}
 {draft&&<section className="card editor sales-editor"><div className="section-heading"><h2>Nova venda</h2><button className="secondary" disabled={busy} onClick={()=>setDraft(false)}>Fechar carrinho</button></div><fieldset disabled={busy} className="sales-fields"><div className="form-grid"><label>Depósito<select aria-label="Depósito da venda" value={warehouse} onChange={e=>{setWarehouse(e.target.value);setProducts([]);}}>{options.warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>Vendedor<select aria-label="Vendedor da venda" value={seller} onChange={e=>setSeller(e.target.value)}>{options.sellers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Buscar cliente<input value={customerQ} onChange={e=>{setCustomerQ(e.target.value);setCustomer('');}} placeholder="Nome ou documento"/></label><label>Cliente<select aria-label="Cliente da venda" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Consumidor não identificado</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 <label className="sales-search">Buscar produto<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, código ou código de barras" maxLength={100}/></label><div className="product-results">{products.map(p=><button type="button" className="product-result secondary" key={p.id} onClick={()=>setCart(lines=>{const old=lines.find(l=>l.id===p.id);return old?lines.map(l=>l.id===p.id?{...l,quantity:((parse(l.quantity,3)??0n)+1000n).toString().padStart(4,'0').replace(/(\d{3})$/,'.$1')}:l):[...lines,{...p,quantity:'1'}];})}><strong>{p.name}</strong><span>{p.code} · {money(p.price)}</span><small>Disponível: {p.stock.replace('.',',')} {p.unit}</small><span>+ Adicionar</span></button>)}</div>
 <h3>Itens da venda</h3>{!cart.length?<p className="empty">Busque e adicione o primeiro produto.</p>:<div className="table-scroll sales-cart"><table><thead><tr><th>Produto</th><th>Quantidade</th><th>Preço unitário</th><th>Ação</th></tr></thead><tbody>{cart.map(l=><tr key={l.id}><td><strong>{l.name}</strong><small>{l.code}</small></td><td><input aria-label={'Quantidade de '+l.name} value={l.quantity} onChange={e=>setCart(lines=>lines.map(p=>p.id===l.id?{...p,quantity:e.target.value}:p))} inputMode="decimal" maxLength={19}/></td><td>{money(l.price)}</td><td><button className="secondary" aria-label={'Remover '+l.name} onClick={()=>setCart(lines=>lines.filter(p=>p.id!==l.id))}>Remover</button></td></tr>)}</tbody></table></div>}
 <div className="form-grid sales-discount"><label>Desconto total (R$)<input inputMode="decimal" value={discount} onChange={e=>setDiscount(e.target.value)} maxLength={19}/></label><label>Motivo do desconto<input value={discountReason} onChange={e=>setDiscountReason(e.target.value)} maxLength={500}/></label></div>
 <div className="sales-total"><span>Subtotal {money(fixed(subtotal))}</span><strong>Total {valid&&cartTotal!==null?money(fixed(cartTotal)):'—'}</strong><small>Salvar não reserva nem baixa estoque. Preços e saldo serão verificados na finalização.</small></div><button disabled={busy||!valid||cartTotal===null||cartTotal<=0n||!warehouse||!seller} onClick={()=>run(async()=>{const r=await api('/api/sales','POST',keyed('create',{warehouseId:warehouse,sellerId:seller,customerId:customer||null,discount,discountReason,items:cart.map(l=>({productId:l.id,quantity:l.quantity,expectedPrice:l.price}))}));await open(r.id);setMessage('Venda aberta. Confira os itens e registre o pagamento.');})}>Salvar venda aberta</button>
 </fieldset></section>}
 {detail&&<section className="card editor sales-detail"><div className="section-heading"><div><h2>Venda #{detail.sale.number}</h2><p className="muted">{statuses[detail.sale.status]} · {detail.sale.customerName??'Consumidor não identificado'}</p></div><button className="secondary" disabled={busy} onClick={()=>setDetail(null)}>Fechar venda</button></div><p className="input-help">Vendedor: {detail.sale.sellerName} · Depósito: {detail.sale.warehouseName} · {new Date(detail.sale.createdAt).toLocaleString('pt-BR',{timeZone:'America/Cuiaba'})} (Cuiabá)</p>
 <div className="table-scroll"><table><thead><tr><th>Produto</th><th>Quantidade</th><th>Preço</th><th>Desconto</th><th>Total</th></tr></thead><tbody>{detail.items.map(l=><tr key={l.id}><td>{l.description}</td><td>{l.quantity.replace('.',',')} {l.unit}</td><td>{money(l.unitPrice)}</td><td>{money(l.discount)}</td><td>{money(l.total)}</td></tr>)}</tbody></table></div><div className="sales-total"><span>Desconto {money(detail.sale.discount)}</span><strong>Total {money(detail.sale.total)}</strong></div>
 {detail.sale.status==='OPEN'&&finalize&&<fieldset disabled={busy} className="sales-fields"><h3>Pagamento</h3><p className="input-help">Informe o valor aplicado à venda em cada método, já descontado o troco. Fiado será disponibilizado na próxima etapa.</p><label>Caixa para pagamento<select aria-label="Caixa para pagamento" value={session} onChange={e=>setSession(e.target.value)}><option value="">Selecione um caixa aberto</option>{cash.sessions.map(s=><option key={s.id} value={s.id}>{s.name} · {s.openedBy}</option>)}</select></label><div className="form-grid sales-discount">{methods.map(([key,label])=><label key={key}>{label}<input inputMode="decimal" value={payments[key]??''} placeholder="0,00" onChange={e=>setPayments(v=>({...v,[key]:e.target.value}))}/></label>)}</div><p className="payment-balance">Falta pagar: <strong>{money(fixed(cents(detail.sale.total)-paid))}</strong></p><button disabled={!session||paid!==cents(detail.sale.total)||methods.some(([m])=>payments[m]&&parse(payments[m],2)===null)} onClick={()=>run(async()=>{await api('/api/sales/'+detail.sale.id+'/finalize','POST',keyed('finalize:'+detail.sale.id,{sessionId:session,payments:methods.filter(([m])=>(parse(payments[m]||'0',2)??0n)>0n).map(([m])=>({method:m,amount:payments[m]}))}));await open(detail.sale.id);setMessage('Venda finalizada. Estoque e pagamentos registrados.');})}>Finalizar venda</button></fieldset>}
 {!!detail.payments.length&&<><h3 className="history-title">Pagamentos registrados</h3>{detail.payments.map(p=><p key={p.id}>{p.direction==='IN'?'Recebimento':'Estorno'} · {methods.find(([m])=>m===p.method)?.[1]} · {money(p.amount)}</p>)}<p className="input-help">O registro não executa transferências bancárias ou estornos na maquininha.</p></>}
 {detail.sale.cancelReason&&<p className="stage-note">Cancelamento: {detail.sale.cancelReason}</p>}
 {(detail.sale.status==='OPEN'||detail.sale.status==='FINALIZED'&&manage)&&<><button className="secondary" disabled={busy} onClick={()=>setShowCancel(v=>!v)}>Cancelar venda</button>{showCancel&&<div className="reversal-form"><p>O cancelamento de uma venda finalizada repõe os itens e registra o estorno integral dos pagamentos. Confirme a devolução física e financeira antes de registrar.</p><label>Motivo do cancelamento<input value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} maxLength={500}/></label>{detail.sale.status==='FINALIZED'&&<label>Caixa para estorno<select aria-label="Caixa para estorno" value={session} onChange={e=>setSession(e.target.value)} disabled={busy}><option value="">Selecione um caixa aberto</option>{cash.sessions.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button disabled={busy||reason.trim().length<5||detail.sale.status==='FINALIZED'&&!session} onClick={()=>run(async()=>{await api('/api/sales/'+detail.sale.id+'/cancel','POST',keyed('cancel:'+detail.sale.id,{reason,...(detail.sale.status==='FINALIZED'?{sessionId:session}:{})}));await open(detail.sale.id);setMessage('Venda cancelada. Histórico preservado.');})}>Confirmar cancelamento</button></div>}</>}
 <p className="stage-note">Registro interno de venda. Não é documento fiscal.</p></section>}
 <div className="catalog-filters"><label>Filtrar vendas<select aria-label="Filtrar vendas" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="ALL">Todas</option><option value="OPEN">Abertas</option><option value="FINALIZED">Finalizadas</option><option value="CANCELLED">Canceladas</option></select></label></div>
 <section className="card users-table catalog-table"><div className="section-heading"><h2>Vendas registradas <span className="count">{total}</span></h2></div>{loading?<p role="status" className="empty">Carregando vendas…</p>:!rows.length?<p className="empty">Nenhuma venda encontrada.</p>:<div className="table-scroll"><table><thead><tr><th>Venda</th><th>Cliente</th><th>Vendedor</th><th>Situação</th><th>Total</th><th>Ação</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><strong>#{s.number}</strong><small>{new Date(s.createdAt).toLocaleDateString('pt-BR',{timeZone:'America/Cuiaba'})}</small></td><td data-label="Cliente">{s.customerName??'Não identificado'}</td><td data-label="Vendedor">{s.sellerName}</td><td data-label="Situação">{statuses[s.status]}</td><td data-label="Total">{money(s.total)}</td><td><button className="secondary" disabled={busy} aria-label={'Abrir venda '+s.number} onClick={()=>open(s.id)}>Ver venda</button></td></tr>)}</tbody></table></div>}<div className="pagination"><span>Página {page}</span><div><button className="secondary" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="secondary" disabled={loading||page*25>=total} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></div></section>
 </>;
}
