import Link from 'next/link';
import { redirect } from 'next/navigation';
import { pageActor } from '../../lib/auth';
export default async function HomePage() {
 const actor=await pageActor(); if(actor.mustChangePassword) redirect('/conta');
 return <><p className="eyebrow">SEU ESPAÇO DE TRABALHO</p><h1>Olá, {actor.name.split(' ')[0]}.</h1><p className="muted page-intro">Seu acesso está pronto. Vamos cuidar dos produtos, clientes e da equipe da loja.</p><section className="welcome-banner"><div><span className="pill">ACESSO CONFIGURADO</span><h2>Cada pessoa, com o acesso certo.</h2><p>Gerencie sua conta e mantenha as responsabilidades da equipe bem definidas.</p><Link className="button light" href="/conta">Cuidar da minha conta <span>↗</span></Link></div><div className="banner-art" aria-hidden="true"><span>✓</span><span>◎</span><span>◇</span></div></section><div className="home-cards">{(actor.permissions.includes('sales.create')||actor.permissions.includes('sales.finalize'))&&<Link className="card action-card" href="/vendas"><span className="card-icon">▣</span><h3>Vendas da loja</h3><p>Prepare o carrinho e registre os pagamentos da venda.</p><strong>Abrir vendas →</strong></Link>}{actor.permissions.includes('products.read')&&<Link className="card action-card" href="/produtos"><span className="card-icon">◇</span><h3>Catálogo de produtos</h3><p>Consulte produtos, preços e categorias da loja.</p><strong>Abrir catálogo →</strong></Link>}{actor.permissions.includes('stock.manage')&&<Link className="card action-card" href="/estoque"><span className="card-icon">▤</span><h3>Controle de estoque</h3><p>Registre entradas e saídas e acompanhe os alertas.</p><strong>Abrir estoque →</strong></Link>}{actor.permissions.includes('customers.read')&&<Link className="card action-card" href="/clientes"><span className="card-icon">♧</span><h3>Clientes da loja</h3><p>Consulte contatos, cadastros e histórico de clientes.</p><strong>Abrir clientes →</strong></Link>}{actor.permissions.includes('users.manage')&&<Link className="card action-card" href="/usuarios"><span className="card-icon">♧</span><h3>Usuários e acessos</h3><p>Cadastre a equipe, defina perfis e gerencie contas ativas.</p><strong>Gerenciar equipe →</strong></Link>}<section className="card"><span className="card-icon">◎</span><h3>Seu perfil</h3><p>{actor.roleName}</p><small className="muted">As permissões são verificadas em cada operação.</small></section></div><p className="stage-note">Em desenvolvimento por etapas. Crédito, parcelas e a gestão financeira completa serão disponibilizados nas próximas entregas.</p></>;
}


